### ISSUE TITLE
Error with group_by when adding extra columns

### ISSUE THREAD

**Issue by lan-k** [gforge/forestplot#60] opened 2023-08-25 08:03 UTC
I found an error using grouped forestplots when extra columns are used beyond the basic labeltext variable next to the forestplot. In the vignette the grouped examples don't use the "labeltext" parameter call.

When modifying the example in the vignette to add the estimate:

```R
library(forestplot)
data(dfHRQoL)


dfHRQoL <-dfHRQoL |>
  mutate(est = sprintf("%.2f", mean), .after = labeltext)

dfHRQoL |>
  group_by(group) |>
  forestplot(labeltext = c(labeltext, est),
             clip = c(-.1, 0.075),
             ci.vertices = TRUE,
             ci.vertices.height = 0.05,
             boxsize = .1,
             xlab = "EQ-5D index") |> 
  fp_add_lines("steelblue") |> 
  fp_add_header(Variable="Variable", est = expression(beta)) |> 
  fp_set_style(box = c("blue", "darkred") |> lapply(function(x) gpar(fill = x, col = "#555555")),
               default = gpar(vertices = TRUE))
```

Gives this error:

Error in forestplot.grouped_df(group_by(dfHRQoL, group), labeltext = c(labeltext,  : 
  There are seem be invalid the labels: 85 vs 65 years > -0.04
 appear in the wrong position.

**Comment by gforge** [comment] 2023-08-26 05:46
This is actually not a bug as you are not intended to use labels that are specific for groups. I've improved the error message that will be released for the next release.

**Closed as completed by gforge** 2023-08-26 05:45 UTC

**Comment by lan-k** [comment] 2023-08-28 00:19
In the previous version, it would print the text for both groups,
separated by commas

----- Original Message -----

**Comment by gforge** [comment] 2023-08-28 10:52
This behavior was probably never intended. I am not even sure how it would work in a predictable manner.

The purpose of the group by is to compare groups visually, if you need the numbers I would recommend having an additional table. I am actually not a fan of including estimates in the forest plot as you can't copy paste the number. If you want a number representation, the tables are awewome
